dataset:
  dataset_path: "C:/Users/migue/Documents/GitHub/Datasets/Experimento"
tokenizer:
  window_size: 512
  stride: 256
dataset_subjects:
  train_subjects: 14
  test_subjects: 3
  validation_subjects: 3
datagen_config:
  combinate_subjects: True
  channel_iters: 300
  target_codification:
    positive: 1
    negative: 0
  dataset: "same_channel"
  #dataset: "same_subject"
  #dataset: "consecutive"
  use_overfitting: True
  subjects_overfitting: 2
  train_dataset_len: 50
dataset_batch:
  train_batch_size: 32
  validation_batch_size: 2
  test_batch_size: 1
  learning_rate: 0.0001
model:
  folder_save: "models"
  extention: ".pt"
  fully_conected: False
loss:
  loss_fuction: "1"
  margin: 0.6
optimizer: "adam"
train:
  load_model: False
  load_model_name: "C:/Users/migue/Documents/GitHub/EmotionNeuralInterface/models/emotion_neural_interface_model-CNN-128-64-32-16-same_channel-margin0.6-P1-loss1-epoch600_dev-thejorseman_1616107236.046163/model-CNN-128-64-32-16-same_channel-margin0.6-P1-loss1-epoch600.pt"
  epochs: 1
  save_each: ""
  #save_each: "100-iter"
validation:
  use_each: ""
  #use_each: "10000-iter"
test:
  use_test: True
  dataset_train: False
github:
  dev: "thejorseman"




