name: "siamese_conv"
layers:
  conv1d1:
    channels_out: 32
    kernel: 8
    stride: 1
    maxpool:
      kernel: 5
      stride: 1
    act_fn: "gelu"
    #act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  conv1d2:
    channels_out: 128
    kernel: 16
    stride: 1
    maxpool:
      kernel: 5
      stride: 2
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv1d3:
    channels_out: 1024
    kernel: 8
    stride: 1
    maxpool:
      kernel: 8
      stride: 2
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv1d4:
    channels_out: 512
    kernel: 8
    stride: 1
    maxpool:
      kernel: 8
      stride: 2
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv1d5:
    channels_out: 256
    kernel: 8
    stride: 1
    maxpool:
      kernel: 8
      stride: 2
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv1d6:
    channels_out: 128
    kernel: 8
    stride: 1
    maxpool:
      kernel: 8
      stride: 2
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  linear1:
    output_dim: 512
    act_fn: "gelu"
    dropout: 0.8
    batch_normalization: True
  linear2:
    output_dim: 128
    act_fn: "none"
    dropout: 0.0
    batch_normalization: True
    output_norm: False
