name: "siamese_linear"
layers:
  linear1:
    output_dim: 256
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  linear3:
    output_dim: 128
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  linear4:
    output_dim: 64
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  linear5:
    output_dim: 128
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  linear6:
    output_dim: 256
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
dropout: 0.3