name: "NedBERT"
d_model: 1024
spatial_conv:
    channels_out: 1024
    kernel: [14,1]
positional_encoding:
  dropout: 0.2
transformer:
  nhead: 4
  num_encoder_layers: 12
  num_decoder_layers: 6
  dim_feedforward: 128
  dropout: 0.1
  activation: "relu"
  batch_first: True
