name: "siamese_stagenet"
spatial_conv:
    channels_out: 14
    kernel: [14,1]
layers:
  conv2d1:
    channels_out: 16
    kernel: [1,50]
    stride: 1
    maxpool:
      kernel: [1,7]
      stride: [1,7]
    #act_fn: "gelu"
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  conv2d2:
    channels_out: 16
    kernel: [1,50]
    stride: 1
    maxpool:
      kernel: [1,7]
      stride: [1,7]
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
  linear1:
    output_dim: 512
    act_fn: "relu"
    dropout: 0.2
    batch_normalization: True
dropout: 0.3
