name: "siamese_stagenet"
spatial_conv:
    channels_out: 14
    kernel: [14,1]
layers:
  conv2d1:
    channels_out: 128
    kernel: [1,16]
    stride: 1
    maxpool:
      kernel: [1,8]
      stride: [1,2]
    #act_fn: "gelu"
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv2d2:
    channels_out: 64
    kernel: [1,12]
    stride: 1
    maxpool:
      kernel: [1,8]
      stride: [1,1]
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv2d3:
    channels_out: 32
    kernel: [1,16]
    stride: 1
    maxpool:
      kernel: [1,8]
      stride: [1,2]
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv2d4:
    channels_out: 16
    kernel: [1,8]
    stride: 1
    maxpool:
      kernel: [1,4]
      stride: [1,1]
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  conv2d5:
    channels_out: 16
    kernel: [1,8]
    stride: 1
    maxpool:
      kernel: [1,4]
      stride: [1,2]
    act_fn: "gelu"
    dropout: 0.2
    batch_normalization: True
  linear1:
    output_dim: 1024
    act_fn: "gelu"
    dropout: 0.8
    batch_normalization: True
  linear2:
    output_dim: 512
    act_fn: "none"
    dropout: 0.8
    batch_normalization: True
dropout: 0.3