name: "siamese_stagenet"
spatial_conv:
    channels_out: 14
    kernel: [14,1]
layers:
  conv2d1:
    channels_out: 128
    kernel: [1,64]
    stride: 1
    maxpool:
      kernel: [1,16]
      stride: 1
    #act_fn: "gelu"
    act_fn: "relu"
    dropout: 0.0
    batch_normalization: True
  conv2d2:
    channels_out: 32
    kernel: [1,128]
    stride: 1
    maxpool:
      kernel: [1,64]
      stride: 1
    act_fn: "relu"
    dropout: 0.0
    batch_normalization: True
  conv2d3:
    channels_out: 16
    kernel: [1,64]
    stride: 1
    maxpool:
      kernel: [1,32]
      stride: 1
    act_fn: "relu"
    dropout: 0.0
    batch_normalization: Trues
  linear1:
    output_dim: 1024
    act_fn: "relu"
    dropout: 0.0
    batch_normalization: True
  linear2:
    output_dim: 256
    act_fn: "relu"
    dropout: 0.0
    batch_normalization: True
dropout: 0.3
